name: zip_modPackage

on:
  push:
    branches:
    - develop
    - feature/*
jobs:
  modCompile:
    name: compile
    runs-on: ubuntu-latest
    steps:
    - name: filename_setup
      run: echo "ZIP_NAME=eam_$(echo '${{ github.ref_name}}' | tr '/' '-').zip" >> $GITHUB_ENV

    - name: repository_check
      uses: actions/checkout@v4

    - name: dir_check
      run: ls -la && ls -la newVersion/*
      
    - name: zip_package
      run: |
        INNER_FOLDER=$(ls newVersion | head -n 1)
        cd "newVersion"
        zip -r "../${{env.ZIP_NAME}}" "$INNER_FOLDER"

    - name: move_to_upload
      run: |
       mkdir upload
       mv ${{ env.ZIP_NAME }} upload/
    
    - name: zip upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIP_NAME }}
        path: upload/


## GOING TO USE IF I WANT TO SCHEDULE
##  schedule:
##  - cron: "0 2 * * 1-6"
