name: zip_modPackage

on:
  push:
    branches:
    - develop
    - feature/*
jobs:
  modCompile:
    name: mod compilation
    runs-on: ubuntu-latest
    steps:
    - name: zip package
      run: zip -r mod.zip ./newVersion/*
    


## GOING TO USE IF I WANT TO SCHEDULE
##  schedule:
##  - cron: "0 2 * * 1-6"
