name: stable_release

on:
  pull_request:
    types:
      - closed
    branches:
      - stable
  push:
    branches:
      - stable
    tags:
      - 'v*'

jobs:
  ## Run this job in case of a push to stable branch
  modCompilePush:
    name: compile_push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: folder_name
      run: |
        SAFE_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
        echo "FOLDER_NAME=$SAFE_NAME" >> $GITHUB_ENV

    - name: checkout_repository
      uses: actions/checkout@v4

    - name: check_contents
      run: ls -la newVersion/

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: eam_${{ env.FOLDER_NAME }}
        path: newVersion/*/

## Run this job in the event of a closed Pull Request (merged)
  modCompilePR:
    name: comple_closed_pr
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: folder_name
      run: |
        SAFE_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
        echo "FOLDER_NAME=$SAFE_NAME" >> $GITHUB_ENV

    - name: checkout_repository
      uses: actions/checkout@v4

    - name: check_contents
      run: ls -la newVersion/

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: eam_${{ env.FOLDER_NAME }}
        path: newVersion/*/

  publishFromPush:
    name: release_push
    if: github.event_name == 'push'
    needs: modCompilePush
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag or branch name
        run: |
          REF_NAME=$(echo "${GITHUB_REF##*/}")
          echo "TAG_NAME=$REF_NAME" >> $GITHUB_ENV

      - name: github_cli
        run: sudo apt install gh

      - name: publish_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh auth setup-git
          gh release create "${{ env.TAG_NAME }}".zip --draft=false

  publishFromPR:
    name: release_pr
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    needs: modCompilePR
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag or branch name
        run: |
          REF_NAME=$(echo "${GITHUB_REF##*/}")
          echo "TAG_NAME=$REF_NAME" >> $GITHUB_ENV

      - name: github_cli
        run: sudo apt install gh

      - name: publish_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh auth setup-git
          gh release create "${{ env.TAG_NAME }}".zip --draft=false

#      - name: Keep only last 5 releases
#        uses: eregon/keep-last-n-releases@v1
#        with:
#          count: 5

    