name: stable_release

on:
  pull_request:
    types:
      - closed
    branches:
      - stable
  push:
    branches:
      - stable

jobs:
  ## Run this job in case of a push to stable branch
  modCompilePush:
    name: compile_push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: folder_name
      run: |
        SAFE_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
        echo "FOLDER_NAME=$SAFE_NAME" >> $GITHUB_ENV

    - name: checkout_repository
      uses: actions/checkout@v4

    - name: check_contents
      run: ls -la newVersion/

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: eam_${{ env.FOLDER_NAME }}
        path: newVersion/*/

## Run this job in the event of a closed Pull Request (merged)
  modCompilePR:
    name: comple_closed_pr
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: folder_name
      run: |
        SAFE_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
        echo "FOLDER_NAME=$SAFE_NAME" >> $GITHUB_ENV

    - name: checkout_repository
      uses: actions/checkout@v4

    - name: check_contents
      run: ls -la newVersion/

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: eam_${{ env.FOLDER_NAME }}
        path: newVersion/*/

  publish:
      name: Publish Release
      needs: [modCompilePush, modCompilePR]
      runs-on: ubuntu-latest
      steps:
      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release edit "${{ needs.release.outputs.tag }}" --draft=false
      - uses: eregon/keep-last-n-releases@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          n: 3
          remove_tags_without_release: true
    